export const data = {
  easy: [
    {q:"Kitab suci umat Islam?", a:"Al-Qur'an"},
    {q:"Bulan puasa?", a:"Ramadhan"},
    {q:"Rukun Islam berapa?", a:"5"},
    {q:"Arah kiblat?", a:"Ka'bah"},
    {q:"Puasa Ramadhan hukumnya?", a:"Wajib"},
    {q:"Shalat wajib sehari semalam berapa?", a:"5"},
    {q:"Hari raya umat Islam setelah Ramadhan?", a:"Idul Fitri"},
    {q:"Nama Nabi yang terakhir?", a:"Muhammad"},
    {q:"Malaikat yang menyampaikan wahyu?", a:"Jibril"},
    {q:"Ibadah haji dilakukan di kota?", a:"Mekah"},
    {q:"Hari raya kurban disebut?", a:"Idul Adha"},
    {q:"Puasa sunnah sebelum Idul Fitri?", a:"Syawal"},
    {q:"Puasa hari Senin dan Kamis sunnah siapa?", a:"Rasulullah"},
    {q:"Rukun iman pertama?", a:"Iman kepada Allah"},
    {q:"Rukun iman kedua?", a:"Iman kepada Malaikat"},
    {q:"Rukun iman ketiga?", a:"Iman kepada Kitab"},
    {q:"Rukun iman keempat?", a:"Iman kepada Rasul"},
    {q:"Rukun iman kelima?", a:"Iman kepada Hari Kiamat"},
    {q:"Shalat Jumat dilakukan setiap?", a:"Jumat"},
    {q:"Nama istri Nabi Muhammad pertama?", a:"Khadijah"},
    {q:"Tempat Nabi Muhammad lahir?", a:"Mekah"},
    {q:"Puasa di bulan Dzulhijjah disebut?", a:"Arafah"},
    {q:"Puasa Ramadhan dimulai dari?", a:"Bulan Ramadhan"},
    {q:"Shalat Subuh terdiri dari berapa rakaat?", a:"2"},
    {q:"Shalat Dzuhur berapa rakaat?", a:"4"},
    {q:"Shalat Ashar berapa rakaat?", a:"4"},
    {q:"Shalat Maghrib berapa rakaat?", a:"3"},
    {q:"Shalat Isya berapa rakaat?", a:"4"},
    {q:"Doa sebelum tidur sunnah siapa?", a:"Rasulullah"},
    {q:"Puasa sunnah Senin dan Kamis untuk siapa?", a:"Umat Islam"},
    {q:"Nama Nabi yang dibakar tetapi selamat?", a:"Ibrahim"},
    {q:"Kota hijrah Nabi Muhammad?", a:"Madinah"},
    {q:"Shalat Tarawih dilakukan pada bulan?", a:"Ramadhan"},
    {q:"Zakat fitrah wajib dibayarkan sebelum?", a:"Idul Fitri"},
    {q:"Rukun haji pertama?", a:"Ihram"},
    {q:"Rukun haji kedua?", a:"Wukuf di Arafah"},
    {q:"Rukun haji ketiga?", a:"Thawaf"},
    {q:"Rukun haji keempat?", a:"Sai'i"},
    {q:"Rukun haji kelima?", a:"Tahallul"},
    {q:"Puasa sunnah hari Asyura tanggal berapa?", a:"10 Muharram"},
    {q:"Puasa sunnah Nabi Daud sehari?", a:"Sehari puasa, sehari tidak"},
    {q:"Nama Nabi yang menerima Taurat?", a:"Musa"},
    {q:"Nama Nabi yang menerima Injil?", a:"Isa"},
    {q:"Kitab terakhir yang diturunkan?", a:"Al-Qur'an"},
    {q:"Hari Jumat doa khusus sunnah siapa?", a:"Rasulullah"},
    {q:"Shalat witir berapa rakaat minimal?", a:"1"},
    {q:"Nabi yang terkenal sabar?", a:"Ayyub"},
    {q:"Nabi yang dibawa ke langit tanpa wafat?", a:"Isa"},
    {q:"Hari kemenangan umat Islam?", a:"Idul Fitri"},
    {q:"Hari pengorbanan umat Islam?", a:"Idul Adha"},
    {q:"Doa bangun tidur sunnah siapa?", a:"Rasulullah"},
    {q:"Nama surah pembuka Al-Qur'an?", a:"Al-Fatihah"},
    {q:"Nama surah terpanjang?", a:"Al-Baqarah"},
    {q:"Nama surah terakhir?", a:"An-Nas"}
  ],

  medium: [
    {q:"Jumlah rakaat shalat sunnah Rawatib sebelum Dzuhur?", a:"4"},
    {q:"Nama ayah Nabi Muhammad?", a:"Abdullah"},
    {q:"Surah pertama yang diturunkan?", a:"Al-'Alaq"},
    {q:"Nabi yang dibakar tetapi selamat?", a:"Ibrahim"},
    {q:"Kapan Isra' Mi'raj terjadi?", a:"Malam"},
    {q:"Hari Asyura jatuh pada tanggal?", a:"10 Muharram"},
    {q:"Nama istri Nabi Muhammad yang pertama?", a:"Khadijah"},
    {q:"Nama malaikat pencatat amal?", a:"Raqib dan Atid"},
    {q:"Lima rukun iman?", a:"Iman kepada Allah, Malaikat, Kitab, Rasul, Hari Kiamat"},
    {q:"Zakat fitrah diberikan sebelum?", a:"Idul Fitri"},
    {q:"Jumlah rukun Islam?", a:"5"},
    {q:"Puasa wajib dilakukan bulan?", a:"Ramadhan"},
    {q:"Shalat sunnah duha minimal rakaat?", a:"2"},
    {q:"Nama Nabi yang membelah laut?", a:"Musa"},
    {q:"Siapa yang menerima wahyu pertama?", a:"Muhammad"},
    {q:"Nama surah yang berisi 255 ayat?", a:"Al-Baqarah"},
    {q:"Rukun haji yang wajib?", a:"Ihram, Wukuf, Thawaf, Sai'i, Tahallul"},
    {q:"Nabi yang dibawa ke langit tanpa wafat?", a:"Isa"},
    {q:"Nama anak Nabi Ibrahim yang terkenal?", a:"Ismail"},
    {q:"Nama istri Nabi Ibrahim yang sabar?", a:"Hajar"},
    {q:"Surah terakhir yang diturunkan?", a:"An-Nas"},
    {q:"Nama Nabi yang terkenal bijaksana?", a:"Sulaiman"},
    {q:"Nabi yang terkenal sabar dalam kesulitan?", a:"Ayyub"},
    {q:"Nama Nabi yang dibunuh oleh kaumnya?", a:"Yunus"},
    {q:"Nama Nabi yang menerima Zabur?", a:"Daud"},
    {q:"Rukun shalat?", a:"Berdiri, Takbir, Ruku, Sujud, Duduk, Salam"},
    {q:"Hari Jumat wajib shalat?", a:"Jumat"},
    {q:"Nabi yang terkenal kedermawanan?", a:"Muhammad"},
    {q:"Puasa sunnah bulan Muharram disebut?", a:"Asyura"},
    {q:"Nama istri Nabi Yusuf?", a:"Zulaikha"},
    {q:"Jumlah ayat Al-Fatihah?", a:"7"},
    {q:"Nama Nabi yang terkenal di Mesir?", a:"Yusuf"},
    {q:"Nama Nabi yang membangun bahtera?", a:"Nuh"},
    {q:"Surah paling pendek?", a:"Al-Kautsar"},
    {q:"Shalat witir berapa rakaat minimal?", a:"1"},
    {q:"Zakat mal diberikan setiap?", a:"Setahun sekali"},
    {q:"Nama malaikat pembawa wahyu?", a:"Jibril"},
    {q:"Nama malaikat pencabut nyawa?", a:"Izrail"},
    {q:"Nama malaikat penjaga surga?", a:"Mikail"},
    {q:"Nama malaikat penjaga neraka?", a:"Raqib dan Atid"},
    {q:"Nama Nabi yang berdoa di Gua Hira?", a:"Muhammad"},
    {q:"Nama Nabi yang terkenal menundukkan Raja?", a:"Sulaiman"},
    {q:"Nama Nabi yang terkenal sabar menunggu janji Tuhan?", a:"Ayub"},
    {q:"Nama Nabi yang terkenal berdoa agar kaumnya selamat?", a:"Nuh"},
    {q:"Jumlah nabi yang disebut dalam Al-Qur'an?", a:"25"},
    {q:"Nabi yang dikenal dengan mukjizat tongkat?", a:"Musa"},
    {q:"Hari kemenangan umat Islam?", a:"Idul Fitri"},
    {q:"Hari pengorbanan umat Islam?", a:"Idul Adha"},
    {q:"Shalat tarawih dilakukan berapa rakaat?", a:"20"}
  ],

  hard: [
    {q:"Nama lengkap Nabi Muhammad ﷺ?", a:"Muhammad bin Abdullah"},
    {q:"Dimana Nabi Muhammad menerima wahyu pertama?", a:"Gua Hira"},
    {q:"Kitab diturunkan kepada Nabi Isa AS?", a:"Injil"},
    {q:"Jumlah Asmaul Husna?", a:"99"},
    {q:"Nama ayah Nabi Ibrahim AS?", a:"Azar"},
    {q:"Siapakah Khalifah kedua?", a:"Umar"},
    {q:"Kota kelahiran Nabi Muhammad?", a:"Mekah"},
    {q:"Surah terpanjang dalam Al-Qur'an?", a:"Al-Baqarah"},
    {q:"Puasa hari Senin dan Kamis termasuk sunnah siapa?", a:"Rasulullah"},
    {q:"Nabi yang terkenal dengan mukjizat tongkat?", a:"Musa"},
    {q:"Nabi yang menyelematkan kaumnya dari banjir besar?", a:"Nuh"},
    {q:"Nabi yang menerima kitab Taurat?", a:"Musa"},
    {q:"Nabi yang menerima kitab Zabur?", a:"Daud"},
    {q:"Nabi yang menerima kitab Injil?", a:"Isa"},
    {q:"Nabi yang menerima Al-Qur'an?", a:"Muhammad"},
    {q:"Nama istri Nabi Muhammad yang terkenal alim?", a:"Aisyah"},
    {q:"Nama istri Nabi Muhammad yang pertama?", a:"Khadijah"},
    {q:"Nama istri Nabi Nuh?", a:"Naamah"},
    {q:"Nabi yang terkenal dengan kesabarannya?", a:"Ayub"},
    {q:"Nabi yang dibawa ke langit tanpa wafat?", a:"Isa"},
    {q:"Jumlah rakaat shalat sunnah rawatib sebelum dan sesudah Dzuhur?", a:"4+2"},
    {q:"Jumlah rakaat shalat sunnah rawatib sebelum dan sesudah Maghrib?", a:"2+2"},
    {q:"Rukun haji wajib berapa?", a:"5"},
    {q:"Nama Nabi yang membelah laut?", a:"Musa"},
    {q:"Nama Nabi yang terkenal bijaksana dan adil?", a:"Sulaiman"},
    {q:"Nama Nabi yang terkenal dengan kesabaran?", a:"Ayub"},
    {q:"Nama Nabi yang dikenal dermawan?", a:"Muhammad"},
    {q:"Surah yang dibaca saat shalat?", a:"Al-Fatihah"},
    {q:"Jumlah ayat Al-Fatihah?", a:"7"},
    {q:"Nama surah terakhir diturunkan?", a:"An-Nas"},
    {q:"Nama surah paling pendek?", a:"Al-Kautsar"},
    {q:"Nama Nabi yang membangun bahtera?", a:"Nuh"},
    {q:"Nama Nabi yang dikenal di Mesir?", a:"Yusuf"},
    {q:"Nama Nabi yang terkenal menundukkan Raja?", a:"Sulaiman"},
    {q:"Nabi yang berdoa agar kaumnya selamat?", a:"Nuh"},
    {q:"Nama malaikat pencatat amal baik?", a:"Raqib"},
    {q:"Nama malaikat pencatat amal buruk?", a:"Atid"},
    {q:"Nama malaikat penjaga surga?", a:"Mikail"},
    {q:"Nama malaikat penjaga neraka?", a:"Izrail"},
    {q:"Jumlah nabi yang disebut dalam Al-Qur'an?", a:"25"},
    {q:"Hari kemenangan umat Islam?", a:"Idul Fitri"},
    {q:"Hari pengorbanan umat Islam?", a:"Idul Adha"},
    {q:"Puasa wajib?", a:"Ramadhan"},
    {q:"Shalat wajib sehari semalam?", a:"5"},
    {q:"Zakat mal diberikan setiap?", a:"Setahun sekali"},
    {q:"Nama Nabi yang terkenal dengan mukjizat tongkat?", a:"Musa"},
    {q:"Surah paling panjang?", a:"Al-Baqarah"},
    {q:"Nama Nabi yang menerima Al-Qur'an?", a:"Muhammad"},
    {q:"Nabi yang dikenal dermawan?", a:"Muhammad"},
    {q:"Nabi yang terkenal sabar menghadapi cobaan?", a:"Ayub"},
    {q:"Nabi yang terkenal bijaksana?", a:"Sulaiman"}
  ]
};
