export const data = {
  agama: [
  { q: "Kitab suci umat Islam adalah?", a: "Al-Qur'an" },
  { q: "Bulan puasa dalam Islam disebut?", a: "Ramadhan" }
  { q: "Nabi terakhir yang diutus Allah SWT adalah?", a: "Nabi Muhammad SAW" },
  { q: "Rukun Islam yang pertama adalah?", a: "Mengucapkan dua kalimat syahadat" },
  { q: "Rukun Islam yang kedua adalah?", a: "Mendirikan shalat" },
  { q: "Jumlah shalat fardhu dalam sehari semalam ada berapa waktu?", a: "Lima" },
  { q: "Berpuasa di bulan apa merupakan rukun Islam yang ketiga?", a: "Ramadhan" },
  { q: "Kiblat umat Islam dalam melaksanakan shalat adalah?", a: "Ka'bah" },
  { q: "Malaikat yang bertugas menyampaikan wahyu kepada para nabi adalah?", a: "Jibril" },
  { q: "Jumlah rukun iman ada?", a: "Enam" },
  { q: "Percaya kepada qada dan qadar termasuk rukun iman yang ke?", a: "Enam" },
  { q: "Siapakah Khulafaur Rasyidin yang pertama?", a: "Abu Bakar Ash-Shiddiq" },
  { q: "Shalat sunnah yang dilakukan saat gerhana matahari adalah?", a: "Shalat Kusuf" },
  { q: "Tempat dilaksanakannya ibadah haji adalah?", a: "Mekkah" },
  { q: "Zakat fitrah wajib dikeluarkan pada bulan?", a: "Ramadhan" },
  { q: "Surat pertama dalam Al-Qur'an adalah?", a: "Al-Fatihah" },
  { q: "Nabi Muhammad SAW lahir di kota?", a: "Mekkah" },
  { q: "Peristiwa perjalanan Nabi Muhammad SAW dari Mekkah ke Madinah disebut?", a: "Hijrah" },
  { q: "Jumlah keseluruhan ayat dalam Al-Qur'an (menurut riwayat Hafs) adalah?", a: "6236" },
  { q: "Hukum shalat jenazah adalah?", a: "Fardhu Kifayah" },
  { q: "Membaca Basmalah merupakan sunnah sebelum melakukan perbuatan baik, apa bacaannya?", a: "Bismillahirrahmanirrahim" },
  { q: "Sifat wajib bagi Allah yang berarti 'berdiri sendiri' adalah?", a: "Qiyamuhu binafsihi" },
  { q: "Peristiwa turunnya Al-Qur'an disebut?", a: "Nuzulul Qur'an" },
  { q: "Nabi yang membuat perahu besar untuk menghadapi banjir bandang adalah?", a: "Nabi Nuh a.s." },
  { q: "Orang yang berhak menerima zakat disebut?", a: "Mustahik" },
  { q: "Dua kalimat syahadat disebut juga Syahadatain, yaitu Syahadat Tauhid dan Syahadat?", a: "Rasul" },
  { q: "Shalat yang diakhiri dengan dua kali salam adalah shalat?", a: "Fardhu/Sunnah" },
  { q: "Sebutan untuk orang yang hafal seluruh Al-Qur'an adalah?", a: "Hafiz/Hafizah" },
  { q: "Nama istri Nabi Muhammad SAW yang pertama adalah?", a: "Khadijah binti Khuwailid" },
  { q: "Puasa sunnah yang dilaksanakan setiap tanggal 13, 14, dan 15 di bulan Hijriah adalah puasa?", a: "Ayyamul Bidh" },
  { q: "Malaikat yang bertugas meniup sangkakala pada hari kiamat adalah?", a: "Isrofil" },
  { q: "Perintah pertama yang diterima Nabi Muhammad SAW dalam wahyu adalah?", a: "Membaca (Iqra)" },
  { q: "Ibadah yang harus dilakukan dengan niat, ihram, tawaf, sa'i, dan wukuf adalah?", a: "Haji" },
  { q: "Nama kitab suci yang diturunkan kepada Nabi Musa a.s. adalah?", a: "Taurat" },
  { q: "Sifat mustahil bagi Allah yang berarti 'tidak ada' adalah?", a: "Adam" },
  { q: "Jumlah rakaat shalat Subuh adalah?", a: "Dua" },
  { q: "Hari raya besar umat Islam setelah Ramadhan adalah?", a: "Idul Fitri" },
  { q: "Hari raya besar umat Islam untuk memperingati kurban adalah?", a: "Idul Adha" },
  { q: "Perilaku jujur dalam Islam disebut?", a: "Siddiq" },
  { q: "Kitab suci Al-Qur'an diturunkan secara berangsur-angsur selama kurang lebih?", a: "23 tahun" },
  { q: "Tempat Nabi Muhammad SAW menerima wahyu pertama adalah di?", a: "Gua Hira" },
  { q: "Percaya kepada adanya malaikat termasuk rukun iman yang ke?", a: "Dua" },
  { q: "Shalat sunnah yang mengiringi shalat fardhu disebut shalat?", a: "Rawatib" },
  { q: "Air yang suci dan mensucikan adalah air?", a: "Mutlak" },
  { q: "Perbuatan menyekutukan Allah SWT dengan sesuatu yang lain disebut?", a: "Syirik" },
  { q: "Malaikat yang mencatat amal baik manusia adalah?", a: "Raqib" },
  { q: "Bacaan setelah shalat yang diawali dengan Subhanallah, Alhamdulillah, Allahu Akbar adalah?", a: "Dzikir" },
  { q: "Pakaian yang digunakan saat ihram bagi laki-laki adalah?", a: "Dua lembar kain tanpa jahitan" },
  { q: "Membaca surah Al-Fatihah dalam shalat adalah termasuk rukun atau sunnah shalat?", a: "Rukun shalat" },
  { q: "Rukun Islam yang kelima (bagi yang mampu) adalah?", a: "Melaksanakan ibadah haji" },
  { q: "Nama lain hari kiamat yang berarti hari pembalasan adalah?", a: "Yaumul Jaza" }
  ],
  inggris: [
  { q: "What is the opposite of 'cold'?", a: "Hot" },
  { q: "Translate 'buku' to English.", a: "Book" }
  { "q": "She ___ (go) to the cinema last night.", "a": "went" },
  { "q": "What is the plural form of 'child'?", "a": "children" },
  { "q": "The opposite of 'huge' is...", "a": "tiny" },
  { "q": "I ___ (study) English for five years now.", "a": "have been studying" },
  { "q": "Which word is an adjective: 'quickly', 'beautifully', or 'happy'?", "a": "happy" },
  { "q": "They ___ (finish) their homework before the teacher arrived.", "a": "had finished" },
  { "q": "What does 'fascinating' mean?", "a": "Extremely interesting" },
  { "q": "If I were rich, I ___ (buy) a new house.", "a": "would buy" },
  { "q": "She is taller ___ her brother.", "a": "than" },
  { "q": "What is the past participle of 'write'?", "a": "written" },
  { "q": "Can you pass me ___ sugar, please?", "a": "some" },
  { "q": "We ___ (watch) a movie when the power went out.", "a": "were watching" },
  { "q": "The synonym for 'brave' is...", "a": "courageous" },
  { "q": "___ is the capital of France?", "a": "What" },
  { "q": "The word 'rapidly' is a(n)...", "a": "adverb" },
  { "q": "The train leaves ___ 8:30 AM.", "a": "at" },
  { "q": "They ___ (not/see) her since Monday.", "a": "haven't seen" },
  { "q": "What does the abbreviation 'CEO' stand for?", "a": "Chief Executive Officer" },
  { "q": "This is the car ___ I bought yesterday.", "a": "which/that" },
  { "q": "If it rains, we ___ (stay) inside.", "a": "will stay" },
  { "q": "The plural form of 'mouse' is?", "a": "mice" },
  { "q": "He is very good ___ playing the piano.", "a": "at" },
  { "q": "The opposite of 'artificial' is...", "a": "natural" },
  { "q": "I wish I ___ (can) fly.", "a": "could" },
  { "q": "The meaning of 'ubiquitous' is...", "a": "Existing or being everywhere at the same time" },
  { "q": "She drives ___ car to work.", "a": "her" },
  { "q": "They ___ (play) football tomorrow afternoon.", "a": "will be playing" },
  { "q": "What is the comparative form of 'good'?", "a": "better" },
  { "q": "A group of fish is called a...", "a": "school" },
  { "q": "The passive form of 'He wrote a book' is: 'A book ___ by him.'", "a": "was written" },
  { "q": "She avoids ___ (eat) unhealthy food.", "a": "eating" },
  { "q": "The opposite of 'optimistic' is...", "a": "pessimistic" },
  { "q": "I'm looking forward ___ (see) you soon.", "a": "to seeing" },
  { "q": "Which tense is used for habitual actions?", "a": "Simple Present" },
  { "q": "What does 'dilemma' mean?", "a": "A difficult situation or problem" },
  { "q": "The store is open ___ Monday ___ Friday.", "a": "from... to" },
  { "q": "If you heat ice, it ___ (melt). (Zero Conditional)", "a": "melts" },
  { "q": "The adjective form of 'knowledge' is...", "a": "knowledgeable" },
  { "q": "She said she ___ (be) tired.", "a": "was" },
  { "q": "The superlative form of 'bad' is?", "a": "worst" },
  { "q": "I'd rather ___ (drink) coffee than tea.", "a": "drink" },
  { "q": "They are going ___ holiday next week.", "a": "on" },
  { "q": "What does the phrase 'break a leg' mean?", "a": "Good luck" },
  { "q": "He ___ (live) in Jakarta since 2010.", "a": "has lived" },
  { "q": "The word 'benevolent' means...", "a": "kind or generous" },
  { "q": "I don't have ___ money.", "a": "much/any" },
  { "q": "She is accustomed ___ (wake) up early.", "a": "to waking" },
  { "q": "The opposite of 'temporary' is...", "a": "permanent" },
  { "q": "If they had studied, they ___ (pass) the exam. (Third Conditional)", "a": "would have passed" },
  { "q": "What is the past tense of 'bear' (menanggung)?", "a": "bore" }
  ],
  matematika: [
  { q: "2 + 2 = ?", a: "4" },
  { q: "10 ÷ 2 = ?", a: "5" }
  { "q": "Berapakah hasil dari $15 \times 8 - 20$?", "a": "100" },
  { "q": "Bentuk pecahan biasa dari $0,25$ adalah?", "a": "1/4" },
  { "q": "Nilai dari $\\sqrt{144}$ adalah?", "a": "12" },
  { "q": "Jika $3x + 5 = 20$, berapakah nilai $x$?", "a": "5" },
  { "q": "Keliling persegi dengan sisi $7$ cm adalah?", "a": "28 cm" },
  { "q": "Berapakah $\\frac{2}{5} + \\frac{1}{10}$?", "a": "1/2" },
  { "q": "Berapakah $5^3$?", "a": "125" },
  { "q": "Suhu awal $5^{\\circ}C$, lalu turun $8^{\\circ}C$. Suhu sekarang adalah?", "a": "-3^{\\circ}C" },
  { "q": "Faktor persekutuan terbesar (FPB) dari $12$ dan $18$ adalah?", "a": "6" },
  { "q": "Berapakah $10\\%$ dari $500$?", "a": "50" },
  { "q": "Luas segitiga dengan alas $10$ cm dan tinggi $6$ cm adalah?", "a": "30 cm$^2$" },
  { "q": "Dalam sebuah deret bilangan $2, 5, 8, 11, \\dots$, suku berikutnya adalah?", "a": "14" },
  { "q": "Hasil dari $(-4) \\times (-7)$ adalah?", "a": "28" },
  { "q": "Sudut lurus memiliki besar?", "a": "180^{\\circ}" },
  { "q": "Berapa menit dalam $3,5$ jam?", "a": "210 menit" },
  { "q": "Jika terdapat data $5, 7, 3, 5, 8, 7, 5$, berapakah modusnya?", "a": "5" },
  { "q": "Berapakah hasil dari $20 \\div 4 + 7$", "a": "12" },
  { "q": "Bentuk desimal dari $35\\%$ adalah?", "a": "0,35" },
  { "q": "Kelipatan persekutuan terkecil (KPK) dari $4$ dan $6$ adalah?", "a": "12" },
  { "q": "Persamaan garis yang melalui titik $(0, 2)$ dengan gradien $3$ adalah?", "a": "y = 3x + 2" },
  { "q": "Berapa sisi yang dimiliki oleh balok?", "a": "6" },
  { "q": "Hasil dari $1 \\frac{1}{2} - \\frac{3}{4}$ adalah?", "a": "3/4" },
  { "q": "Nilai rata-rata dari $4, 6, 8, 2$ adalah?", "a": "5" },
  { "q": "Jika sisi sebuah kubus adalah $3$ cm, berapakah volumenya?", "a": "27 cm$^3$" },
  { "q": "Bentuk baku dari $150.000$ adalah?", "a": "$1,5 \\times 10^5$" },
  { "q": "Sebuah lingkaran memiliki diameter $14$ cm. Berapakah jari-jarinya?", "a": "7 cm" },
  { "q": "Hasil dari $(-10) + 3$ adalah?", "a": "-7" },
  { "q": "Jika $a=4$ dan $b=3$, berapakah nilai $2a + b$?", "a": "11" },
  { "q": "Berapakah $\\frac{1}{3}$ dari $90$?", "a": "30" },
  { "q": "Jumlah sudut dalam segitiga adalah?", "a": "180^{\\circ}" },
  { "q": "Tanda yang tepat untuk membandingkan $-5$ dan $-2$ adalah?", "a": "$<$" },
  { "q": "Median dari data $2, 4, 6, 8, 10$ adalah?", "a": "6" },
  { "q": "Jika sebuah tas didiskon $20\\%$ dari harga $100.000$. Berapa harga setelah diskon?", "a": "Rp80.000" },
  { "q": "Hasil dari $9 \\times 9 - 1$ adalah?", "a": "80" },
  { "q": "Penyelesaian dari pertidaksamaan $2x > 10$ adalah?", "a": "$x > 5$" },
  { "q": "Berapakah sudut komplemen dari $60^{\\circ}$?", "a": "30^{\\circ}$" },
  { "q": "Bentuk pecahan campuran dari $\\frac{7}{3}$ adalah?", "a": "$2 \\frac{1}{3}$" },
  { "q": "Hasil dari $8^2 + 6^2$ adalah?", "a": "100" },
  { "q": "Dalam segitiga siku-siku, sisi terpanjang disebut?", "a": "Hipotenusa" },
  { "q": "Berapakah selisih antara $100$ dan $(-30)$?", "a": "130" },
  { "q": "Himpunan bilangan prima kurang dari $10$ adalah?", "a": "$\{2, 3, 5, 7\}$" },
  { "q": "Luas persegi panjang dengan panjang $12$ cm dan lebar $5$ cm adalah?", "a": "60 cm$^2$" },
  { "q": "Hasil dari $100 \\div (-25)$ adalah?", "a": "-4" },
  { "q": "Jika $x = 2$, berapakah nilai dari $x^2 + 5x - 1$?", "a": "13" },
  { "q": "Rata-rata dari $10$ dan $20$ adalah?", "a": "15" },
  { "q": "Skala peta $1:100.000$. Jarak di peta $5$ cm. Jarak sebenarnya adalah?", "a": "5 km" },
  { "q": "Berapakah $(3 + 4) \\times 2$?", "a": "14" },
  { "q": "Sebuah kubus memiliki luas permukaan $96$ cm$^2$. Berapa panjang sisinya?", "a": "4 cm" },
  { "q": "Hasil dari $\\frac{1}{4} \\times 8$ adalah?", "a": "2" },
  { "q": "Dalam koordinat Kartesius, titik $(3, -2)$ berada di kuadran?", "a": "IV" }
  ],
  indonesia: [
  { q: "Antonim dari 'besar' adalah?", a: "Kecil" },
  { q: "Sinonim dari 'cantik' adalah?", a: "Indah" }
  { "q": "Kata dasar dari 'melakukan' adalah?", "a": "laku" },
  { "q": "Jenis kalimat yang mengandung perintah atau larangan adalah kalimat?", "a": "Imperatif" },
  { "q": "Awalan yang menunjukkan makna 'berbuat atau menjadi' adalah?", "a": "ber-" },
  { "q": "Sinonim dari kata 'pintar' adalah?", "a": "pandai/cerdas" },
  { "q": "Kata yang baku untuk 'apotik' adalah?", "a": "apotek" },
  { "q": "Unsur utama dalam kalimat (setelah subjek) adalah?", "a": "predikat" },
  { "q": "Jenis teks yang menceritakan urutan kejadian atau peristiwa adalah?", "a": "Narasi" },
  { "q": "Antonim dari kata 'mahal' adalah?", "a": "murah" },
  { "q": "Penulisan yang benar untuk singkatan 'dan lain-lain' adalah?", "a": "dll." },
  { "q": "Kalimat aktif diubah menjadi kalimat pasif, predikatnya menggunakan imbuhan?", "a": "di-" },
  { "q": "Tanda baca yang digunakan untuk mengakhiri kalimat berita adalah?", "a": "titik (.)" },
  { "q": "Jenis paragraf yang isinya membujuk atau mengajak pembaca adalah?", "a": "Persuasi" },
  { "q": "Apa yang dimaksud dengan 'peribahasa'?", "a": "Kelompok kata yang tetap susunannya dan mengandung aturan berperilaku" },
  { "q": "Kata 'sejarah' yang seharusnya berimbuhan untuk 'mempelajari riwayat masa lalu' adalah?", "a": "mensejarahkan/bersejarah" },
  { "q": "Tanda baca yang dipakai di antara unsur-unsur dalam suatu perincian adalah?", "a": "koma (,)" },
  { "q": "Tema utama atau gagasan pokok suatu paragraf disebut?", "a": "Ide pokok/Gagasan utama" },
  { "q": "Kata 'cinta' adalah jenis kata?", "a": "Benda/Nomina" },
  { "q": "Sinonim dari kata 'dusta' adalah?", "a": "bohong" },
  { "q": "Sistem tanda-tanda yang disepakati untuk dipakai dalam bahasa tulis disebut?", "a": "Ejaan" },
  { "q": "Kalimat yang menggunakan kata penghubung 'kemudian' termasuk jenis konjungsi?", "a": "Temporal" },
  { "q": "Kata tidak baku dari 'nasehat' adalah?", "a": "nasihat" },
  { "q": "Apa fungsi utama dari kamus?", "a": "Mencari makna kata" },
  { "q": "Majas yang membandingkan dua hal yang berbeda secara langsung tanpa kata 'seperti' adalah?", "a": "Metafora" },
  { "q": "Apa yang dimaksud dengan 'puisi'?", "a": "Ragam sastra yang bahasanya terikat oleh irama, matra, rima, serta penyusunan larik dan bait" },
  { "q": "Predikat dalam kalimat 'Ayah membaca koran' adalah?", "a": "membaca" },
  { "q": "Imbuhan yang berarti 'tempat' adalah?", "a": "-an (misal: lapangan)" },
  { "q": "Jenis kata yang berfungsi menerangkan kata kerja, kata sifat, atau kata keterangan lain adalah?", "a": "Adverbia/Kata keterangan" },
  { "q": "Kata baku dari 'rubah' (dalam konteks berubah) adalah?", "a": "ubah" },
  { "q": "Majas yang melebih-lebihkan kenyataan disebut?", "a": "Hiperbola" },
  { "q": "Pola kalimat dasar yang paling sederhana adalah?", "a": "S-P (Subjek-Predikat)" },
  { "q": "Akhiran yang menunjukkan pelaku atau profesi adalah?", "a": "-wan/-man" },
  { "q": "Teks yang bertujuan memberikan petunjuk atau panduan melakukan sesuatu adalah?", "a": "Prosedur" },
  { "q": "Singkatan 'Yth.' merupakan singkatan dari?", "a": "Yang terhormat" },
  { "q": "Kata yang baku untuk 'ijazah' adalah?", "a": "ijasah" },
  { "q": "Apa yang dimaksud dengan 'kalimat majemuk'?", "a": "Kalimat yang memiliki lebih dari satu pola kalimat" },
  { "q": "Sebutan untuk orang yang pekerjaannya mengumpulkan berita untuk media massa adalah?", "a": "Wartawan" },
  { "q": "Jenis karangan yang berisi pendapat pribadi penulis tentang suatu masalah adalah?", "a": "Argumentasi/Opini" },
  { "q": "Pronomina yang digunakan untuk orang ketiga tunggal adalah?", "a": "Dia/Ia/Beliau" },
  { "q": "Apa yang dimaksud dengan 'homonim'?", "a": "Kata yang sama bunyi dan tulisannya tetapi berbeda maknanya" },
  { "q": "Bentuk kata ulang yang mengalami perubahan bunyi (misal: sayur-mayur) disebut?", "a": "Dwi-purwa/Kata ulang berimbuhan" },
  { "q": "Perubahan bentuk kata dari 'bertemu' menjadi 'temu' disebut proses?", "a": "Afiksasi/Pembentukan kata" },
  { "q": "Teks yang bertujuan mendeskripsikan suatu objek secara rinci adalah?", "a": "Deskripsi" },
  { "q": "Unsur yang dijelaskan oleh predikat dalam kalimat pasif adalah?", "a": "Subjek" },
  { "q": "Kata sambung yang menghubungkan dua kalimat setara (misal: dan, atau) disebut?", "a": "Konjungsi koordinatif" },
  { "q": "Dalam tata bahasa, 'kambing hitam' termasuk jenis?", "a": "Frasa/Idiom" },
  { "q": "Singkatan resmi dari 'Perseroan Terbatas' adalah?", "a": "PT" },
  { "q": "Sebuah paragraf yang kalimat utamanya berada di akhir paragraf disebut?", "a": "Induktif" },
  { "q": "Jenis teks yang berisi fakta dan data secara objektif adalah?", "a": "Eksposisi" },
  { "q": "Penggunaan huruf kapital yang benar untuk nama hari adalah?", "a": "Senin/Selasa/Rabu (Kapital di awal)" },
  { "q": "Majas yang menggunakan kata 'seperti' atau 'laksana' untuk membandingkan adalah?", "a": "Simile" }
  ]
};


