export const data = {
  agama: [
  { q: "Kitab suci umat Islam adalah?", a: "Al-Qur'an" },
  { q: "Bulan puasa dalam Islam disebut?", a: "Ramadhan" },
  { q: "Nabi terakhir yang diutus Allah SWT adalah?", a: "Nabi Muhammad SAW" },
  { q: "Rukun Islam yang pertama adalah?", a: "Mengucapkan dua kalimat syahadat" },
  { q: "Rukun Islam yang kedua adalah?", a: "Mendirikan shalat" },
  { q: "Jumlah shalat fardhu dalam sehari semalam ada berapa waktu?", a: "Lima" },
  { q: "Berpuasa di bulan apa merupakan rukun Islam yang ketiga?", a: "Ramadhan" },
  { q: "Kiblat umat Islam dalam melaksanakan shalat adalah?", a: "Ka'bah" },
  { q: "Malaikat yang bertugas menyampaikan wahyu kepada para nabi adalah?", a: "Jibril" },
  { q: "Jumlah rukun iman ada?", a: "Enam" },
  { q: "Percaya kepada qada dan qadar termasuk rukun iman yang ke?", a: "Enam" },
  { q: "Siapakah Khulafaur Rasyidin yang pertama?", a: "Abu Bakar Ash-Shiddiq" },
  { q: "Shalat sunnah yang dilakukan saat gerhana matahari adalah?", a: "Shalat Kusuf" },
  { q: "Tempat dilaksanakannya ibadah haji adalah?", a: "Mekkah" },
  { q: "Zakat fitrah wajib dikeluarkan pada bulan?", a: "Ramadhan" },
  { q: "Surat pertama dalam Al-Qur'an adalah?", a: "Al-Fatihah" },
  { q: "Nabi Muhammad SAW lahir di kota?", a: "Mekkah" },
  { q: "Peristiwa perjalanan Nabi Muhammad SAW dari Mekkah ke Madinah disebut?", a: "Hijrah" },
  { q: "Jumlah keseluruhan ayat dalam Al-Qur'an (menurut riwayat Hafs) adalah?", a: "6236" },
  { q: "Hukum shalat jenazah adalah?", a: "Fardhu Kifayah" },
  { q: "Membaca Basmalah merupakan sunnah sebelum melakukan perbuatan baik, apa bacaannya?", a: "Bismillahirrahmanirrahim" },
  { q: "Sifat wajib bagi Allah yang berarti 'berdiri sendiri' adalah?", a: "Qiyamuhu binafsihi" },
  { q: "Peristiwa turunnya Al-Qur'an disebut?", a: "Nuzulul Qur'an" },
  { q: "Nabi yang membuat perahu besar untuk menghadapi banjir bandang adalah?", a: "Nabi Nuh a.s." },
  { q: "Orang yang berhak menerima zakat disebut?", a: "Mustahik" },
  { q: "Dua kalimat syahadat disebut juga Syahadatain, yaitu Syahadat Tauhid dan Syahadat?", a: "Rasul" },
  { q: "Shalat yang diakhiri dengan dua kali salam adalah shalat?", a: "Fardhu/Sunnah" },
  { q: "Sebutan untuk orang yang hafal seluruh Al-Qur'an adalah?", a: "Hafiz/Hafizah" },
  { q: "Nama istri Nabi Muhammad SAW yang pertama adalah?", a: "Khadijah binti Khuwailid" },
  { q: "Puasa sunnah yang dilaksanakan setiap tanggal 13, 14, dan 15 di bulan Hijriah adalah puasa?", a: "Ayyamul Bidh" },
  { q: "Malaikat yang bertugas meniup sangkakala pada hari kiamat adalah?", a: "Isrofil" },
  { q: "Perintah pertama yang diterima Nabi Muhammad SAW dalam wahyu adalah?", a: "Membaca (Iqra)" },
  { q: "Ibadah yang harus dilakukan dengan niat, ihram, tawaf, sa'i, dan wukuf adalah?", a: "Haji" },
  { q: "Nama kitab suci yang diturunkan kepada Nabi Musa a.s. adalah?", a: "Taurat" },
  { q: "Sifat mustahil bagi Allah yang berarti 'tidak ada' adalah?", a: "Adam" },
  { q: "Jumlah rakaat shalat Subuh adalah?", a: "Dua" },
  { q: "Hari raya besar umat Islam setelah Ramadhan adalah?", a: "Idul Fitri" },
  { q: "Hari raya besar umat Islam untuk memperingati kurban adalah?", a: "Idul Adha" },
  { q: "Perilaku jujur dalam Islam disebut?", a: "Siddiq" },
  { q: "Kitab suci Al-Qur'an diturunkan secara berangsur-angsur selama kurang lebih?", a: "23 tahun" },
  { q: "Tempat Nabi Muhammad SAW menerima wahyu pertama adalah di?", a: "Gua Hira" },
  { q: "Percaya kepada adanya malaikat termasuk rukun iman yang ke?", a: "Dua" },
  { q: "Shalat sunnah yang mengiringi shalat fardhu disebut shalat?", a: "Rawatib" },
  { q: "Air yang suci dan mensucikan adalah air?", a: "Mutlak" },
  { q: "Perbuatan menyekutukan Allah SWT dengan sesuatu yang lain disebut?", a: "Syirik" },
  { q: "Malaikat yang mencatat amal baik manusia adalah?", a: "Raqib" },
  { q: "Bacaan setelah shalat yang diawali dengan Subhanallah, Alhamdulillah, Allahu Akbar adalah?", a: "Dzikir" },
  { q: "Pakaian yang digunakan saat ihram bagi laki-laki adalah?", a: "Dua lembar kain tanpa jahitan" },
  { q: "Membaca surah Al-Fatihah dalam shalat adalah termasuk rukun atau sunnah shalat?", a: "Rukun shalat" },
  { q: "Rukun Islam yang kelima (bagi yang mampu) adalah?", a: "Melaksanakan ibadah haji" },
  { q: "Nama lain hari kiamat yang berarti hari pembalasan adalah?", a: "Yaumul Jaza" },
  ],
  inggris: [
  { q: "What is the opposite of 'cold'?", a: "Hot" },
  { q: "Translate 'buku' to English.", a: "Book" },
  { q: "She ___ (go) to the cinema last night.", a: "went" },
  { q: "What is the plural form of 'child'?", a: "children" },
  { q: "The opposite of 'huge' is...", a: "tiny" },
  { q: "I ___ (study) English for five years now.", a: "have been studying" },
  { q: "Which word is an adjective: 'quickly', 'beautifully', or 'happy'?", a: "happy" },
  { q: "They ___ (finish) their homework before the teacher arrived.", a: "had finished" },
  { q: "What does 'fascinating' mean?", a: "Extremely interesting" },
  { q: "If I were rich, I ___ (buy) a new house.", a: "would buy" },
  { q: "She is taller ___ her brother.", a: "than" },
  { q: "What is the past participle of 'write'?", a: "written" },
  { q: "Can you pass me ___ sugar, please?", a: "some" },
  { q: "We ___ (watch) a movie when the power went out.", a: "were watching" },
  { q: "The synonym for 'brave' is...", a: "courageous" },
  { q: "___ is the capital of France?", a: "What" },
  { q: "The word 'rapidly' is a(n)...", a: "adverb" },
  { q: "The train leaves ___ 8:30 AM.", a: "at" },
  { q: "They ___ (not/see) her since Monday.", a: "haven't seen" },
  { q: "What does the abbreviation 'CEO' stand for?", a: "Chief Executive Officer" },
  { q: "This is the car ___ I bought yesterday.", a: "which/that" },
  { q: "If it rains, we ___ (stay) inside.", a: "will stay" },
  { q: "The plural form of 'mouse' is?", a: "mice" },
  { q: "He is very good ___ playing the piano.", a: "at" },
  { q: "The opposite of 'artificial' is...", a: "natural" },
  { q: "I wish I ___ (can) fly.", a: "could" },
  { q: "The meaning of 'ubiquitous' is...", a: "Existing or being everywhere at the same time" },
  { q: "She drives ___ car to work.", a: "her" },
  { q: "They ___ (play) football tomorrow afternoon.", a: "will be playing" },
  { q: "What is the comparative form of 'good'?", a: "better" },
  { q: "A group of fish is called a...", a: "school" },
  { q: "The passive form of 'He wrote a book' is: 'A book ___ by him.'", a: "was written" },
  { q: "She avoids ___ (eat) unhealthy food.", a: "eating" },
  { q: "The opposite of 'optimistic' is...", a: "pessimistic" },
  { q: "I'm looking forward ___ (see) you soon.", a: "to seeing" },
  { q: "Which tense is used for habitual actions?", a: "Simple Present" },
  { q: "What does 'dilemma' mean?", a: "A difficult situation or problem" },
  { q: "The store is open ___ Monday ___ Friday.", a: "from... to" },
  { q: "If you heat ice, it ___ (melt). (Zero Conditional)", a: "melts" },
  { q: "The adjective form of 'knowledge' is...", a: "knowledgeable" },
  { q: "She said she ___ (be) tired.", a: "was" },
  { q: "The superlative form of 'bad' is?", a: "worst" },
  { q: "I'd rather ___ (drink) coffee than tea.", a: "drink" },
  { q: "They are going ___ holiday next week.", a: "on" },
  { q: "What does the phrase 'break a leg' mean?", a: "Good luck" },
  { q: "He ___ (live) in Jakarta since 2010.", a: "has lived" },
  { q: "The word 'benevolent' means...", a: "kind or generous" },
  { q: "I don't have ___ money.", a: "much/any" },
  { q: "She is accustomed ___ (wake) up early.", a: "to waking" },
  { q: "The opposite of 'temporary' is...", a: "permanent" },
  { q: "If they had studied, they ___ (pass) the exam. (Third Conditional)", a: "would have passed" },
  { q: "What is the past tense of 'bear' (menanggung)?", a: "bore" },
  ],
  matematika: [
    { q: "Hasil dari 12 + 8 adalah?", a: "20" },
    { q: "Berapakah 15 × 3?", a: "45" },
    { q: "Hasil dari 100 ÷ 4 adalah?", a: "25" },
    { q: "Berapakah 9² ?", a: "81" },
    { q: "Akar kuadrat dari 49 adalah?", a: "7" },
    { q: "Urutan pecahan dari kecil ke besar: 1/2, 3/4, 1/3 adalah?", a: "1/3, 1/2, 3/4" },
    { q: "Nilai dari 3 × (4 + 5) adalah?", a: "27" },
    { q: "Jika 2x = 10, maka nilai x adalah?", a: "5" },
    { q: "Hasil dari 15% dari 200 adalah?", a: "30" },
    { q: "Bilangan prima terkecil adalah?", a: "2" },
    { q: "Rumus luas persegi adalah?", a: "s × s" },
    { q: "Rumus keliling lingkaran adalah?", a: "2 × π × r" },
    { q: "Jika panjang = 6 cm dan lebar = 4 cm, luas persegi panjang adalah?", a: "24" },
    { q: "Hasil dari 0,25 × 100 adalah?", a: "25" },
    { q: "Sudut siku-siku besarnya adalah?", a: "90 derajat" },
    { q: "Hasil dari 8 + 12 × 2 adalah?", a: "32" },
    { q: "Rata-rata dari 5, 10, 15 adalah?", a: "10" },
    { q: "Jika ¾ dari suatu bilangan adalah 12, maka bilangan itu adalah?", a: "16" },
    { q: "Nilai dari 5³ adalah?", a: "125" },
    { q: "Sebuah segitiga memiliki alas 8 cm dan tinggi 5 cm. Luasnya?", a: "20" },
    { q: "Jika 1 jam = 60 menit, maka 2,5 jam = ... menit?", a: "150" },
    { q: "Bilangan ganjil setelah 27 adalah?", a: "29" },
    { q: "Urutan bilangan kelipatan 4 yang kurang dari 20?", a: "4, 8, 12, 16" },
    { q: "Hasil dari 6! (faktorial) adalah?", a: "720" },
    { q: "Sebuah toko memberi diskon 10% dari Rp20000, harga setelah diskon?", a: "18000" },
    { q: "Hasil dari 7 × 8 adalah?", a: "56" },
    { q: "Nilai tempat angka 5 pada 4521 adalah?", a: "Ratusan" },
    { q: "Nilai 2⁴ adalah?", a: "16" },
    { q: "Hasil dari 100 − 37 adalah?", a: "63" },
    { q: "Berapa hasil dari 0,5 + 0,25?", a: "0,75" },
    { q: "Sisi kubus panjangnya 10 cm, volumenya adalah?", a: "1000" },
    { q: "Keliling segitiga sama sisi dengan sisi 9 cm adalah?", a: "27" },
    { q: "Jika suhu naik dari 25°C menjadi 33°C, maka kenaikan suhu adalah?", a: "8" },
    { q: "Nilai dari (12 − 4) × 3 adalah?", a: "24" },
    { q: "Berapakah hasil dari 5/10 + 2/10?", a: "7/10" },
    { q: "Jika tabungan awal Rp100.000 ditambah 20%, maka totalnya?", a: "120000" },
    { q: "Berapakah hasil 0,6 × 50?", a: "30" },
    { q: "Keliling persegi panjang 12 cm × 8 cm adalah?", a: "40" },
    { q: "Jika sebuah segitiga memiliki sudut 50° dan 70°, maka sudut ketiganya?", a: "60" },
    { q: "Nilai dari 15² − 10² adalah?", a: "125" },
    { q: "Jika 4 pensil = Rp4000, maka 10 pensil = ?", a: "10000" },
    { q: "Satuan dari luas adalah?", a: "cm²" },
    { q: "Sebuah mobil menempuh 240 km dalam 4 jam. Kecepatan rata-rata?", a: "60" },
    { q: "Hasil dari 18 ÷ 3 × 2 adalah?", a: "12" },
    { q: "Jika panjang diagonal persegi 14,14 cm, maka sisinya?", a: "10" },
    { q: "Jika 30% dari suatu bilangan adalah 90, maka bilangan itu?", a: "300" },
    { q: "Konversi 0,75 ke bentuk pecahan sederhana adalah?", a: "3/4" },
    { q: "Nilai π (pi) dibulatkan dua desimal adalah?", a: "3.14" },
    { q: "Hasil dari 25 × 4 − 50 adalah?", a: "50" },
    { q: "Jumlah sudut pada segitiga adalah?", a: "180 derajat" },
    { q: "Jika 10 liter air dituangkan ke 5 botol sama besar, tiap botol berisi?", a: "2" },
  ],
  indonesia: [
  { q: "Antonim dari 'besar' adalah?", a: "Kecil" },
  { q: "Sinonim dari 'cantik' adalah?", a: "Indah" },
  { q: "Kata dasar dari 'melakukan' adalah?", a: "laku" },
  { q: "Jenis kalimat yang mengandung perintah atau larangan adalah kalimat?", a: "Imperatif" },
  { q: "Awalan yang menunjukkan makna 'berbuat atau menjadi' adalah?", a: "ber-" },
  { q: "Sinonim dari kata 'pintar' adalah?", a: "pandai/cerdas" },
  { q: "Kata yang baku untuk 'apotik' adalah?", a: "apotek" },
  { q: "Unsur utama dalam kalimat (setelah subjek) adalah?", a: "predikat" },
  { q: "Jenis teks yang menceritakan urutan kejadian atau peristiwa adalah?", a: "Narasi" },
  { q: "Antonim dari kata 'mahal' adalah?", a: "murah" },
  { q: "Penulisan yang benar untuk singkatan 'dan lain-lain' adalah?", a: "dll." },
  { q: "Kalimat aktif diubah menjadi kalimat pasif, predikatnya menggunakan imbuhan?", a: "di-" },
  { q: "Tanda baca yang digunakan untuk mengakhiri kalimat berita adalah?", a: "titik (.)" },
  { q: "Jenis paragraf yang isinya membujuk atau mengajak pembaca adalah?", a: "Persuasi" },
  { q: "Apa yang dimaksud dengan 'peribahasa'?", a: "Kelompok kata yang tetap susunannya dan mengandung aturan berperilaku" },
  { q: "Kata 'sejarah' yang seharusnya berimbuhan untuk 'mempelajari riwayat masa lalu' adalah?", a: "mensejarahkan/bersejarah" },
  { q: "Tanda baca yang dipakai di antara unsur-unsur dalam suatu perincian adalah?", a: "koma (,)" },
  { q: "Tema utama atau gagasan pokok suatu paragraf disebut?", a: "Ide pokok/Gagasan utama" },
  { q: "Kata 'cinta' adalah jenis kata?", a: "Benda/Nomina" },
  { q: "Sinonim dari kata 'dusta' adalah?", a: "bohong" },
  { q: "Sistem tanda-tanda yang disepakati untuk dipakai dalam bahasa tulis disebut?", a: "Ejaan" },
  { q: "Kalimat yang menggunakan kata penghubung 'kemudian' termasuk jenis konjungsi?", a: "Temporal" },
  { q: "Kata tidak baku dari 'nasehat' adalah?", a: "nasihat" },
  { q: "Apa fungsi utama dari kamus?", a: "Mencari makna kata" },
  { q: "Majas yang membandingkan dua hal yang berbeda secara langsung tanpa kata 'seperti' adalah?", a: "Metafora" },
  { q: "Apa yang dimaksud dengan 'puisi'?", a: "Ragam sastra yang bahasanya terikat oleh irama, matra, rima, serta penyusunan larik dan bait" },
  { q: "Predikat dalam kalimat 'Ayah membaca koran' adalah?", a: "membaca" },
  { q: "Imbuhan yang berarti 'tempat' adalah?", a: "-an (misal: lapangan)" },
  { q: "Jenis kata yang berfungsi menerangkan kata kerja, kata sifat, atau kata keterangan lain adalah?", a: "Adverbia/Kata keterangan" },
  { q: "Kata baku dari 'rubah' (dalam konteks berubah) adalah?", a: "ubah" },
  { q: "Majas yang melebih-lebihkan kenyataan disebut?", a: "Hiperbola" },
  { q: "Pola kalimat dasar yang paling sederhana adalah?", a: "S-P (Subjek-Predikat)" },
  { q: "Akhiran yang menunjukkan pelaku atau profesi adalah?", a: "-wan/-man" },
  { q: "Teks yang bertujuan memberikan petunjuk atau panduan melakukan sesuatu adalah?", a: "Prosedur" },
  { q: "Singkatan 'Yth.' merupakan singkatan dari?", a: "Yang terhormat" },
  { q: "Kata yang baku untuk 'ijazah' adalah?", a: "ijasah" },
  { q: "Apa yang dimaksud dengan 'kalimat majemuk'?", a: "Kalimat yang memiliki lebih dari satu pola kalimat" },
  { q: "Sebutan untuk orang yang pekerjaannya mengumpulkan berita untuk media massa adalah?", a: "Wartawan" },
  { q: "Jenis karangan yang berisi pendapat pribadi penulis tentang suatu masalah adalah?", a: "Argumentasi/Opini" },
  { q: "Pronomina yang digunakan untuk orang ketiga tunggal adalah?", a: "Dia/Ia/Beliau" },
  { q: "Apa yang dimaksud dengan 'homonim'?", a: "Kata yang sama bunyi dan tulisannya tetapi berbeda maknanya" },
  { q: "Bentuk kata ulang yang mengalami perubahan bunyi (misal: sayur-mayur) disebut?", a: "Dwi-purwa/Kata ulang berimbuhan" },
  { q: "Perubahan bentuk kata dari 'bertemu' menjadi 'temu' disebut proses?", a: "Afiksasi/Pembentukan kata" },
  { q: "Teks yang bertujuan mendeskripsikan suatu objek secara rinci adalah?", a: "Deskripsi" },
  { q: "Unsur yang dijelaskan oleh predikat dalam kalimat pasif adalah?", a: "Subjek" },
  { q: "Kata sambung yang menghubungkan dua kalimat setara (misal: dan, atau) disebut?", a: "Konjungsi koordinatif" },
  { q: "Dalam tata bahasa, 'kambing hitam' termasuk jenis?", a: "Frasa/Idiom" },
  { q: "Singkatan resmi dari 'Perseroan Terbatas' adalah?", a: "PT" },
  { q: "Sebuah paragraf yang kalimat utamanya berada di akhir paragraf disebut?", a: "Induktif" },
  { q: "Jenis teks yang berisi fakta dan data secara objektif adalah?", a: "Eksposisi" },
  { q: "Penggunaan huruf kapital yang benar untuk nama hari adalah?", a: "Senin/Selasa/Rabu (Kapital di awal)" },
  { q: "Majas yang menggunakan kata 'seperti' atau 'laksana' untuk membandingkan adalah?", a: "Simile" },
  ],
};








